spring:
  datasource:
    password: password
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/beerservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: beer_service
